### ISSUE TITLE
Update to 2.3

### ISSUE THREAD

**Issue by lsorber** [conda-forge/hug-feedstock#1]
Can't conda install Hug with Python 3.6 right now because:
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - hug -> falcon 1.0.0 -> python 2.7* -> vc 9
  - python >=3.6
Use "conda info <package>" to see the dependencies for each package.
```

Hug 2.3 is out since May 4 (which uses falcon 1.3). Would one of the maintainers be so kind as to upgrade the conda-forge package? Thanks!

**Comment by gerrymanoim** [comment]
It looks like the [github page](https://github.com/timothycrosley/hug/releases) doesn't tag 2.3.1 or 2.3.2 which [PiPy](https://pypi.python.org/pypi/hug/) has as the latest version. Can the recipe be switched to pull from there rather than the github archives? 

Happy to fork and PR if that's alright.

**Comment by kwilcox** [comment]
Done here: https://github.com/conda-forge/hug-feedstock/pull/2
